# Generated by Django 5.2.4 on 2025-08-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_city_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='addres',
        ),
    ]
