# Generated by Django 5.2.4 on 2025-08-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_address_order_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres',
            new_name='address',
        ),
    ]
