# Generated by Django 4.2.19 on 2025-09-14 13:02

import datetime
from django.db import migrations
import django_jalali.db.models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_address_postal_code_profile_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/no_image.jpg', force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to=''),
        ),
    ]
